<a href="https://colab.research.google.com/github/Suryaprakash17/letsupgrade-DS-advance/blob/main/DSd4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import scipy.linalg as la
import copy

# 1. Eigenvalues and Eigenvectors

Function:
The function scipy.linalg.eig computes eigenvalues and eigenvectors of a square matrix 

Syntax: 
numpy.linalg.eig(a)

Code:

In [9]:
a=np.array([[1,2],[3,4]])
print(a)
print() 
r=la.eig(a)
print(r[0]) #eigenvalues
print()
print(r[1]) #eigenvectors

[[1 2]
 [3 4]]

[-0.37228132+0.j  5.37228132+0.j]

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# 2.digitize()

Function: digitize() method, we can get the indices of the bins to which the each value is belongs to an array by using np. 

 Syntax : np.digitize(Array, Bin, Right)

Code:

In [11]:
b = np.array([1.2, 2.4, 3.6, 4.8]) 
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0])  
r=np.digitize(b,bins) 
print(r)

[1 2 3 4]


# 3.repeat()

Function: for loops are traditionally used when you have a block of code which you want to repeat a fixed number of times. The Python for statement iterates over the members of a sequence in order, executing the block each time.

Syntax: numpy.repeat(arr, repetitions, axis = None)


Code:

In [13]:
ar = np.arange(5) 
print("Array : \n", ar) 
  
repetitions = 2
r = np.repeat(ar, repetitions) 
print("\nRepeating array 2 times : \n", r) 
print("Shape is : ", r.shape) 
  
repetitions = 3
r = np.repeat(ar, repetitions) 
print("\nRepeating array 3 times : \n", r) 
print("Shape is : ", r.shape)

Array : 
 [0 1 2 3 4]

Repeating array 2 times : 
 [0 0 1 1 2 2 3 3 4 4]
Shape is :  (10,)

Repeating array 3 times : 
 [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4]
Shape is :  (15,)


# 4.squeeze()

Function: squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

Syntax: arr : [array_like] Input array.
 

Code:

In [15]:
in_ar = np.array([[[2, 2, 2], [2, 2, 2]]]) 
print ("Input array : ",in_ar)  
print("Shape of input array : ",in_ar.shape)   
out_ar = np.squeeze(in_ar)  
print ("Output squeezed array : ", out_ar) 
print("Shape of the output array : ", out_ar.shape)  


Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
Output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of the output array :  (2, 3)


# 5. linespace()

Function: Linspace is an in-built function in Python's NumPy library.
It is used to create an evenly spaced sequence in a specified interval.


Syntax: numpy.linspace(start,
               stop,
               num = 50,
               endpoint = True,
               retstep = False,
               dtype = None)

Code:

In [17]:
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n") # restep set to True 
x = np.linspace(0, 3, 10) # To evaluate sin() in long range 
print("A\n", np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.3271947  0.6183698  0.84147098 0.9719379  0.99540796
 0.90929743 0.72308588 0.45727263 0.14112001]


# 6.clip()

Function: clip() function is used to Clip (limit) the values in an array. Given an interval, values outside the interval are clipped to the interval edges.

Syntax: numpy.clip(a, a_min, a_max, out=None)



Code:

In [18]:
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ] 
print ("Input array : ", in_array) 
  
out_array = np.clip(in_array, a_min = 2, a_max = 6) 
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


#7.extract()

Function: extract() function is used to extract capture groups in the regex pat as columns in a DataFrame. For each subject string in the Series, extract groups from the first match of regular expression pat. Parameter : pat : Regular expression pattern with capturing groups.


Syntax: numpy.extract(condition, array)




Code:

In [20]:
arr = np.arange(10).reshape(5, 2) 
print("Original array is :\n", arr) 
r = np.mod(arr, 4) !=0
print("\nArray Condition r is :\n", r) # This will show element status of satisfying condition 
print("\nElements that satisfy condition r  : \n", np.extract(r, arr)) # This will return elements that satisy condition "r" condition 
r1 = arr - 4 == 1
print("\nArray Condition r1 :\n", r1) # This will show element status of satisfying condition
print("\nElements that satisfy condition r1  : \n", np.extract(r1, arr)) # This will return elements that satisy condition "r1" condition 


Original array is :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Array Condition r is :
 [[False  True]
 [ True  True]
 [False  True]
 [ True  True]
 [False  True]]

Elements that satisfy condition r  : 
 [1 2 3 5 6 7 9]

Array Condition r1 :
 [[False False]
 [False False]
 [False  True]
 [False False]
 [False False]]

Elements that satisfy condition r1  : 
 [5]


#8.argpartition()

Function: argpartition() in Python. numpy. argpartition() function is used to create a indirect partitioned copy of input array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array.


Syntax: numpy.argpartition(arr, kth, axis=-1, kind=’introselect’, order=None)

Code:

In [21]:
in_arr = np.array([[ 2, 0,  1], [ 5, 4, 9] ]) 
print ("Input array : \n", in_arr)  
out_arr = np.argpartition(in_arr, 1, axis = 1) 
print ("Output partitioned array indices :\n ", out_arr) 

Input array : 
 [[2 0 1]
 [5 4 9]]
Output partitioned array indices :
  [[1 2 0]
 [1 0 2]]


#9.setdiff1d()

Function: setdiff1d() function in Python. numpy. setdiff1d() function find the set difference of two arrays and return the unique values in arr1 that are not in arr2.


Syntax: numpy.setdiff1d(arr1, arr2, assume_unique = False)



Code:

In [22]:
arr1 = [5, 6, 2, 3, 4] 
arr2 = [1, 2, 3] 
result = np.setdiff1d(arr1, arr2) 
print(result) 


[4 5 6]


#10.Itemsize

Function: Itemsize attribute return the size of the dtype of the item of the underlying data for the given Series object.

Syntax: numpy.ndarray.itemsize(arr)



Code:

In [24]:
arr = np.array([1, 2, 3, 4]) 
result = arr.itemsize 
print(result)

8


#11.hstack()

Function: hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array. Parameters : tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the second axis.


Syntax: numpy.hstack(tup)



Code:

In [25]:
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


#12.vstack()

Function: vstack() function is used to stack the sequence of input arrays vertically to make a single array. Parameters : tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the first axis.

Syntax: numpy.vstack(tup)



Code:

In [26]:
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
 
out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


#13.hsplit()

Function: hsplit() function. The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise). hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.


Syntax: numpy.hsplit(arr, indices_or_sections)


Code:

In [28]:
arr = np.arange(16.0).reshape(4, 4) 
result = np.hsplit(arr, 2) 
print(result)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


#14.vsplit()

Function: numpy.vsplit() function split an array into multiple sub-arrays vertically (row-wise). vsplit is equivalent to split with axis=0 (default), the array is always split along the first axis regardless of the array dimension.



Syntax: numpy.vsplit(arr, indices_or_sections)


Code:

In [29]:
arr = np.arange(9.0).reshape(3, 3) 
result = np.vsplit(arr, 1) 
print(result) 


[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


#15.View vs Shallow Copy

Function: It is less obvious what a shallow copy of a NumPy array should contain. A view of a NumPy array is a shallow copy in sense A, i.e. it references the same data buffer as the original, so changes to the original data affect the view data and vice versa.


Syntax: copy.copy()

Code:

In [37]:
li1 = [1, 2, [3,5], 4] 
  
# using copy to shallow copy  
li2 = copy.copy(li1) 
  
# original elements of list 
print ("The original elements before shallow copying") 
for i in range(0,len(li1)): 
    print (li1[i],end=" ") 
  
print("\r") 
  
# adding and element to new list 
li2[2][0] = 7
  
# checking if change is reflected 
print ("The original elements after shallow copying") 
for i in range(0,len( li1)): 
    print (li1[i],end=" ")

The original elements before shallow copying
1 2 [3, 5] 4 
The original elements after shallow copying
1 2 [7, 5] 4 

#16.Deep Copy

Function: In case of deep copy, a copy of object is copied in other object. It means that any changes made to a copy of object do not reflect in the original object. In python, this is implemented using “deepcopy()” function.


Syntax: copy.deepcopy()




Code:

In [36]:
li1 = [1, 2, [3,5], 4] 
  
li2 = copy.deepcopy(li1) 
   
print ("The original elements before deep copying") 
for i in range(0,len(li1)): 
    print (li1[i],end=" ") 
  
print("\r") 
 
li2[2][0] = 7
 
print ("The new list of elements after deep copying ") 
for i in range(0,len( li1)): 
    print (li2[i],end=" ") 
  
print("\r") 
print ("The original elements after deep copying") 
for i in range(0,len( li1)): 
    print (li1[i],end=" ") 


The original elements before deep copying
1 2 [3, 5] 4 
The new list of elements after deep copying 
1 2 [7, 5] 4 
The original elements after deep copying
1 2 [3, 5] 4 

#17.copy()

Function: copy() returns a copy of the array. Parameters: order : Controls the memory layout of the copy. 'C' means C-order, 'F' means F-order, 'A' means 'F' if a is Fortran contiguous, 'C' otherwise.



Syntax: numpy.ndarray.copy(order=’C’)



Code:

In [30]:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7]], order ='F') 
print("x is: \n", x) 
y = x.copy() 
print("y is :\n", y) 
print("\nx is copied to y") 


x is: 
 [[0 1 2 3]
 [4 5 6 7]]
y is :
 [[0 1 2 3]
 [4 5 6 7]]

x is copied to y


#18.meshgrid()

Function: meshgrid() in Python. The numpy module of Python provides meshgrid() function for creating a rectangular grid with the help of the given 1-D arrays that represent the Matrix indexing or Cartesian indexing.


Syntax: numpy.meshgrid(*xi, **kwargs)  


Code:

In [31]:
na, nb = (5, 3)  
a = np.linspace(1, 2, na)  
b = np.linspace(1, 2, nb)  
xa, xb = np.meshgrid(a, b)  
xa  
xb

array([[1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

#19.swapaxes()

Function: numpy. swapaxes (a, axis1, axis2)[source] Interchange two axes of an array. Parameters aarray_like. Input array.


Syntax: numpy.swapaxes(arr, axis1, axis2)


Code:

In [32]:
arr = np.array([[2, 4, 6]]) 
result = np.swapaxes(arr, 0, 1) 
print(result)

[[2]
 [4]
 [6]]


#20.column_stack()

Function: column_stack() in Python. numpy. column_stack() function is used to stack 1-D arrays as columns into a 2-D array.It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is,just like with hstack function.


Syntax: numpy.column_stack(tup)



Code:

In [33]:
in_arr1 = np.array(( 1, 2, 3 )) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array(( 4, 5, 6 )) 
print ("2nd Input array : \n", in_arr2)  
    
out_arr = np.column_stack((in_arr1, in_arr2)) 
print ("Output stacked array:\n ", out_arr) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output stacked array:
  [[1 4]
 [2 5]
 [3 6]]
